### ISSUE TITLE
Launcher not detecting Half Life 2 requirements 

### ISSUE THREAD

**Issue by fate6** [Bitl/GENESYS-Launcher#2]
The launcher is unable to confirm ownership or install of Half-Life 2 or the Source SDK Base 2013
![issue hl2](https://user-images.githubusercontent.com/1782499/99630275-6d70db00-29ee-11eb-8dc5-711cf9d5530f.png)

**Comment by Bitl** [comment]
Fixed with https://github.com/Bitl/GENESYS-Launcher/commit/ec49ed2c93bcd873bcab7a6cfdc9827faf2f58d5
